### ISSUE TITLE
Aboutを改善してください。

### ISSUE THREAD

**Issue by koko1928** [Liberluna/LiberChat#60]
@EdamAme-x Aboutの文章に絵文字などを使用するのはなるべく控えて頂きたいです。
改善案: Liberlunaが贈る、自由なチャットサービス"Liberchat"。どなたでもご利用になれます。

**Comment by koko1928** [comment]
@EdamAme-x まだ改善されていないように見受けられますが、、、

**Comment by EdamAme-x** [comment]
ん、どつした
